# 生产配置文件
server:
  port: 9098

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/secure?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      auto-commit: true
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    database: 0
    host: 192.168.56.8
    port: 6300
    password: 123456
    timeout: 300ms
    lettuce:
      pool:
        max-wait: 10ms
        max-active: 30
        min-idle: 3

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: cn.zfc.entity
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名
      logic-delete-value: true
      logic-not-delete-value: false

logging:
  config: classpath:logback-spring.xml
  level:
    cn:
      zfc:
        mapper: debug


